# Generated by Django 4.2.7 on 2026-07-20 18:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Numeric score (0.00 – 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('letter_grade', models.CharField(blank=True, choices=[('A+', 'A+ (97-100)'), ('A', 'A  (93-96)'), ('A-', 'A- (90-92)'), ('B+', 'B+ (87-89)'), ('B', 'B  (83-86)'), ('B-', 'B- (80-82)'), ('C+', 'C+ (77-79)'), ('C', 'C  (73-76)'), ('C-', 'C- (70-72)'), ('D', 'D  (60-69)'), ('F', 'F  (0-59)'), ('I', 'Incomplete'), ('W', 'Withdrawn')], default='', max_length=2)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks from the teacher')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile')),
                ('teacher', models.ForeignKey(help_text='Teacher who entered this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-graded_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
